CREATE TABLE posts (
  id VARCHAR(16) PRIMARY KEY,
  week INT NOT NULL,
  slot INT NOT NULL,
  username VARCHAR(64),
  username_en VARCHAR(64),
  handle VARCHAR(64),
  avatar_color VARCHAR(16),
  image_url VARCHAR(255),
  image_url_en VARCHAR(255),
  caption TEXT,
  caption_en TEXT,
  likes INT,
  is_true TINYINT(1),
  source VARCHAR(64),
  source_url VARCHAR(255),
  observe_prompt TEXT,
  observe_prompt_en TEXT,
  challenge_prompt TEXT,
  challenge_prompt_en TEXT,
  alternative_prompt TEXT,
  alternative_prompt_en TEXT,
  image_description	TEXT,
  image_description_en TEXT
);